# Generated by Django 3.2.7 on 2022-01-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_course', '0001_initial'),
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='online_course',
            field=models.ManyToManyField(to='online_course.OnlineCourse'),
        ),
    ]
