# Generated by Django 3.2.7 on 2022-01-18 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='biography',
            field=models.TextField(blank=True, default='جایی برای معرفی خودتان...', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
