# Generated by Django 3.2.7 on 2022-01-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='slider_content',
            new_name='slider_alt',
        ),
    ]
