# Generated by Django 3.2.7 on 2022-01-18 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_audience',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='course_duration',
            field=models.DurationField(default=datetime.timedelta(days=1, seconds=57600)),
        ),
        migrations.AddField(
            model_name='course',
            name='course_file',
            field=models.FileField(blank=True, default='', null=True, upload_to='files/course_files/'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_prerequisites',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='course_syllabus',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='course_targets',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_info',
            field=models.TextField(default=''),
        ),
    ]
