# Generated by Django 3.2.7 on 2022-01-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20220118_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_audience',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_info',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_prerequisites',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_syllabus',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_targets',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
