# Generated by Django 3.2.7 on 2022-01-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20220118_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='online_course_status',
            field=models.CharField(choices=[('pre-registration', 'Pre Registration'), ('running', 'Running'), ('done', 'Done')], default='running', max_length=100),
        ),
    ]
