# Generated by Django 3.2.7 on 2022-01-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_related_category',
            field=models.ManyToManyField(related_name='rel_cat', to='course.CourseCategory'),
        ),
    ]
