# Generated by Django 3.2.7 on 2022-01-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_course_course_related_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_discount_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='course_discounted_price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_price',
            field=models.IntegerField(default=1),
        ),
    ]
