# Generated by Django 3.2.7 on 2022-01-22 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogUserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User logged in'), ('delete_object', 'User delete object'), ('create_object', 'User create object'), ('buy_object', 'User buy object')], default='login', max_length=20, verbose_name='action')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('ip', models.GenericIPAddressField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Action log',
                'verbose_name_plural': 'Actions log',
                'ordering': ['-date'],
            },
        ),
    ]
