# Generated by Django 3.2.7 on 2022-02-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loguserinfo',
            name='action',
            field=models.CharField(choices=[('login', 'User logged in'), ('delete_object', 'User delete object'), ('create_object', 'User create object'), ('buy_object', 'User buy object'), ('log_out', 'User logged out'), ('sign_up', 'User signed up'), ('failed', 'User failed to loging in')], default='login', max_length=20, verbose_name='action'),
        ),
    ]
