# Generated by Django 4.0.2 on 2022-02-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_log', '0003_alter_loguserinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loguserinfo',
            name='action',
            field=models.CharField(choices=[('logged in', 'logged in'), ('delete something', 'delete something'), ('create something', 'create something'), ('buy something', 'buy something'), ('logged out', 'logged out'), ('signed up', 'signed up'), ('failed to log in', 'failed to log in')], default='log_in', max_length=20, verbose_name='action'),
        ),
    ]
