# Generated by Django 3.2.7 on 2022-02-08 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event_log', '0005_alter_loguserinfo_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='loguserinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
