# Generated by Django 3.2.7 on 2022-02-08 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_log', '0006_loguserinfo_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loguserinfo',
            name='created',
        ),
    ]
