# Generated by Django 3.2.7 on 2022-02-09 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_log', '0008_alter_loguserinfo_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogUserInfo',
            new_name='LogUserActivity',
        ),
    ]
