# Generated by Django 3.2.7 on 2022-02-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_log', '0010_auto_20220209_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='loguseractivity',
            name='os',
            field=models.CharField(default='windows', max_length=100),
        ),
    ]
