# Generated by Django 3.2.7 on 2022-02-09 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_log', '0011_loguseractivity_os'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loguseractivity',
            old_name='browser',
            new_name='user_agent',
        ),
        migrations.RemoveField(
            model_name='loguseractivity',
            name='device',
        ),
        migrations.RemoveField(
            model_name='loguseractivity',
            name='os',
        ),
    ]
