# Generated by Django 3.2.7 on 2022-01-17 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online_course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title_fani', models.CharField(max_length=50)),
                ('code_fani', models.CharField(default='1234567890', max_length=10)),
                ('code_academy', models.CharField(default='1234567890', max_length=10)),
                ('certificate_image_academy', models.ImageField(blank=True, null=True, upload_to='store_image/certificate_academy_image/')),
                ('certificate_image_fani', models.ImageField(blank=True, null=True, upload_to='store_image/certificate_fani_image/')),
                ('fani_score', models.PositiveIntegerField(default='100')),
                ('academy_score', models.PositiveIntegerField(default='100')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('online_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='online_course.onlinecourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
