# Generated by Django 3.2.7 on 2022-02-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('consultation_type', models.CharField(choices=[('branding and marketing', 'برندیگ و مارکتینگ'), ('website development and designment', 'طراحی و پیاده سازی سایت')], max_length=100)),
                ('description', models.TextField()),
                ('brand_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('meeting_type', models.CharField(choices=[('in person', 'حضوری'), ('online', 'آنلاین')], max_length=100)),
                ('how_to_know', models.CharField(max_length=100)),
            ],
        ),
    ]
