# Generated by Django 3.2.7 on 2022-02-12 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsultForm',
            new_name='ConsultationForm',
        ),
    ]
