# Generated by Django 3.2.7 on 2022-02-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0002_rename_consultform_consultationform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationform',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
