# Generated by Django 3.2.7 on 2022-02-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0003_alter_consultationform_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationform',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultationform',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
