# Generated by Django 3.2.7 on 2022-02-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0004_auto_20220212_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationform',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consultationform',
            name='consultation_type',
            field=models.CharField(choices=[('social media', 'شبکه های اجتماعی'), ('content production', 'تولید محتوا'), ('website development and designment', 'طراحی و پیاده سازی سایت')], max_length=100),
        ),
        migrations.AlterField(
            model_name='consultationform',
            name='how_to_know',
            field=models.CharField(choices=[('search in internet', 'سرج در اینترنت'), ('social media', 'شبکه اجتماعی'), ('introduced by friends', 'معرفی دوستان')], default='شبکه اجتماعی', max_length=100),
        ),
    ]
