# Generated by Django 3.2.7 on 2022-01-21 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_order', models.IntegerField(default=1)),
                ('chapter_title', models.CharField(default='', max_length=100)),
                ('chapter_description', models.TextField(default='')),
                ('chapter_duration', models.TimeField(default=0)),
                ('number_of_episode', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_course_name', models.CharField(default='', max_length=100)),
                ('online_course_price', models.IntegerField(default=1)),
                ('online_course_description', models.TextField(default='')),
                ('online_course_duration', models.DurationField(default=172800.0)),
                ('online_course_date', models.DateTimeField(auto_now_add=True)),
                ('online_course_image', models.ImageField(default='', upload_to='images/')),
                ('number_of_videos', models.IntegerField(default=1)),
                ('online_course_level', models.CharField(choices=[('مبتدی', 'Beginner'), ('متوسط', 'Intermediate'), ('حرفه ای', 'Proffessional')], default='مبتدی', max_length=100)),
                ('online_course_status', models.CharField(choices=[('پیش ثبت نام', 'Pre Registration'), ('درحال برگزاری', 'Being Held'), ('برگزار شده', 'Was Held')], default='درحال برگزاری', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User logged in'), ('delete_object', 'User delete object'), ('create_object', 'User create object'), ('buy_object', 'User buy object')], default='login', max_length=20, verbose_name='action')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Action log',
                'verbose_name_plural': 'Actions log',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_order', models.IntegerField(default=1)),
                ('episode_title', models.CharField(default='', max_length=100)),
                ('episode_description', models.TextField(default='')),
                ('episode_duration', models.TimeField(default=0)),
                ('episode_file', models.FileField(default='', upload_to='files/')),
                ('episode_related_to', models.ManyToManyField(to='online_course.Chapter')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_related_to',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='online_course.onlinecourse'),
        ),
    ]
