# Generated by Django 3.2.7 on 2022-01-17 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_order', models.IntegerField(default=1)),
                ('chapter_title', models.CharField(default='', max_length=100)),
                ('chapter_description', models.TextField(default='')),
                ('chapter_duration', models.TimeField(default='')),
                ('number_of_episode', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_course_name', models.CharField(default='', max_length=100)),
                ('online_course_price', models.IntegerField(default=1)),
                ('online_course_description', models.TextField(default='')),
                ('online_course_duration', models.DurationField(default=172800.0)),
                ('online_course_date', models.DateTimeField(auto_now_add=True)),
                ('online_course_image', models.ImageField(default='', upload_to='images/')),
                ('number_of_videos', models.IntegerField(default=1)),
                ('online_course_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('proffessional', 'Proffessional')], default='beginner', max_length=100)),
                ('online_course_start_date', models.DateTimeField(auto_now_add=True)),
                ('online_course_teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_order', models.IntegerField(default=1)),
                ('episode_title', models.CharField(default='', max_length=100)),
                ('episode_description', models.TextField(default='')),
                ('episode_duration', models.TimeField(default='')),
                ('episode_related_to', models.ManyToManyField(to='online_course.Chapter')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_related_to',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='online_course.onlinecourse'),
        ),
    ]
