# Generated by Django 3.2.7 on 2022-01-22 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_course', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyLog',
        ),
    ]
