# Generated by Django 3.2.7 on 2022-02-09 10:05

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('online_course', '0002_delete_mylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinecourse',
            name='online_course_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
