# Generated by Django 3.2.7 on 2022-01-25 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_course', '0005_onlinecoursecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinecourse',
            name='online_course_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online_course.onlinecoursecategory'),
        ),
    ]
