# Generated by Django 3.2.7 on 2022-01-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_course', '0006_onlinecourse_online_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinecourse',
            name='online_course_related_category',
            field=models.ManyToManyField(related_name='online_rel_cat', to='online_course.OnlineCourseCategory'),
        ),
    ]
