# Generated by Django 3.2.7 on 2022-01-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_course', '0007_onlinecourse_online_course_related_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinecourse',
            name='online_course_discount_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='onlinecourse',
            name='online_course_discounted_price',
            field=models.IntegerField(default=1),
        ),
    ]
